# CMake generated Testfile for 
# Source directory: /Users/qiaoyifan/mysql-server/storage/perfschema/unittest
# Build directory: /Users/qiaoyifan/mysql-server/storage/perfschema/unittest
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(pfs_instr_class "/Users/qiaoyifan/mysql-server/runtime_output_directory/pfs_instr_class-t")
set_tests_properties(pfs_instr_class PROPERTIES  _BACKTRACE_TRIPLES "/Users/qiaoyifan/mysql-server/cmake/mysql_add_executable.cmake;116;ADD_TEST;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;30;MYSQL_ADD_EXECUTABLE;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;48;PFS_ADD_TEST;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;0;")
add_test(pfs_instr_class-oom "/Users/qiaoyifan/mysql-server/runtime_output_directory/pfs_instr_class-oom-t")
set_tests_properties(pfs_instr_class-oom PROPERTIES  _BACKTRACE_TRIPLES "/Users/qiaoyifan/mysql-server/cmake/mysql_add_executable.cmake;116;ADD_TEST;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;30;MYSQL_ADD_EXECUTABLE;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;48;PFS_ADD_TEST;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;0;")
add_test(pfs_instr "/Users/qiaoyifan/mysql-server/runtime_output_directory/pfs_instr-t")
set_tests_properties(pfs_instr PROPERTIES  _BACKTRACE_TRIPLES "/Users/qiaoyifan/mysql-server/cmake/mysql_add_executable.cmake;116;ADD_TEST;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;30;MYSQL_ADD_EXECUTABLE;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;48;PFS_ADD_TEST;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;0;")
add_test(pfs_instr-oom "/Users/qiaoyifan/mysql-server/runtime_output_directory/pfs_instr-oom-t")
set_tests_properties(pfs_instr-oom PROPERTIES  _BACKTRACE_TRIPLES "/Users/qiaoyifan/mysql-server/cmake/mysql_add_executable.cmake;116;ADD_TEST;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;30;MYSQL_ADD_EXECUTABLE;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;48;PFS_ADD_TEST;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;0;")
add_test(pfs_account-oom "/Users/qiaoyifan/mysql-server/runtime_output_directory/pfs_account-oom-t")
set_tests_properties(pfs_account-oom PROPERTIES  _BACKTRACE_TRIPLES "/Users/qiaoyifan/mysql-server/cmake/mysql_add_executable.cmake;116;ADD_TEST;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;30;MYSQL_ADD_EXECUTABLE;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;48;PFS_ADD_TEST;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;0;")
add_test(pfs_host-oom "/Users/qiaoyifan/mysql-server/runtime_output_directory/pfs_host-oom-t")
set_tests_properties(pfs_host-oom PROPERTIES  _BACKTRACE_TRIPLES "/Users/qiaoyifan/mysql-server/cmake/mysql_add_executable.cmake;116;ADD_TEST;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;30;MYSQL_ADD_EXECUTABLE;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;48;PFS_ADD_TEST;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;0;")
add_test(pfs_user-oom "/Users/qiaoyifan/mysql-server/runtime_output_directory/pfs_user-oom-t")
set_tests_properties(pfs_user-oom PROPERTIES  _BACKTRACE_TRIPLES "/Users/qiaoyifan/mysql-server/cmake/mysql_add_executable.cmake;116;ADD_TEST;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;30;MYSQL_ADD_EXECUTABLE;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;48;PFS_ADD_TEST;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;0;")
add_test(pfs_noop "/Users/qiaoyifan/mysql-server/runtime_output_directory/pfs_noop-t")
set_tests_properties(pfs_noop PROPERTIES  _BACKTRACE_TRIPLES "/Users/qiaoyifan/mysql-server/cmake/mysql_add_executable.cmake;116;ADD_TEST;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;30;MYSQL_ADD_EXECUTABLE;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;48;PFS_ADD_TEST;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;0;")
add_test(pfs "/Users/qiaoyifan/mysql-server/runtime_output_directory/pfs-t")
set_tests_properties(pfs PROPERTIES  _BACKTRACE_TRIPLES "/Users/qiaoyifan/mysql-server/cmake/mysql_add_executable.cmake;116;ADD_TEST;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;30;MYSQL_ADD_EXECUTABLE;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;48;PFS_ADD_TEST;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;0;")
add_test(pfs_misc "/Users/qiaoyifan/mysql-server/runtime_output_directory/pfs_misc-t")
set_tests_properties(pfs_misc PROPERTIES  _BACKTRACE_TRIPLES "/Users/qiaoyifan/mysql-server/cmake/mysql_add_executable.cmake;116;ADD_TEST;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;30;MYSQL_ADD_EXECUTABLE;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;48;PFS_ADD_TEST;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;0;")
add_test(pfs_connect_attr "/Users/qiaoyifan/mysql-server/runtime_output_directory/pfs_connect_attr-t")
set_tests_properties(pfs_connect_attr PROPERTIES  _BACKTRACE_TRIPLES "/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;74;ADD_TEST;/Users/qiaoyifan/mysql-server/storage/perfschema/unittest/CMakeLists.txt;0;")
